### ISSUE TITLE
line 27 error in main.dart code

### ISSUE THREAD

**Issue by aihamhasan** [londonappbrewery/quizzler-flutter#11]
class _QuizPageState extends State<QuizPage> {

error: Classes can only extend other classes
![Screenshot (31)](https://user-images.githubusercontent.com/32892955/86237282-1ee6af80-bbb9-11ea-9404-b8e470eb91e1.png)

**Comment by kt-aakash** [comment]
Are you sure about:
1) Properly pulling the project from GitHub
2) Running **get dependencies** without error

I see warnings like "Material App isn't defined"
